### ISSUE TITLE
Top 30D?

### ISSUE THREAD

**Issue by runsolidbuddy** [ShaderWave/RandomClipPlayer#4]
Hi! First off, I wanted to start by saying I really, _really_, love this, and I have already started using it in my stream as an end screen at the end of stream displaying different top clips before the stream ends/raid another channel. The users' names are on in the display, to potentially encourage users to clip events/moments on stream and share them to get their name on stream.  It looks so good and I massively appreciate this <3 

I think it would be even better if I was able to show just the top from the last 30-day period as an option! I was looking through the code, and without much knowledge about the Twitch dev api, I wasn't sure how I would do it. Would that be something that could be incorporated?

**Comment by ShaderWave** [comment]
Thanks for the feedback! I'll look into this and see if it's possible to add.

**Comment by ShaderWave** [comment]
Twitch API seems to offer a `started_at` and `ended_at` parameter for filtering the clips search, presumably returning only clips created between those two dates, and so getting clips made in the last 30 days should be possible.

**Comment by runsolidbuddy** [comment]
> Twitch API seems to offer a `started_at` and `ended_at` parameter for filtering the clips search, presumably returning only clips created between those two dates, and so getting clips made in the last 30 days should be possible.

Alright, thank you! I may look into a it to see what I can do. Again, really appreciate it!!
